name: SrEssentials
author: PAS123 und ClientConnection at WorldCrafter
version: 0.1
main: de.worldcrafter.sressentials.SrEssentials
website: https://worldcrafter.de/
commands: 
  gm:
  gamemode:
  tp:
  teleport:
  tph:
  tphere:
  spawn:
  warp: 
  mwarp:
  wb:
  workbench:
  ec:
  enderchest:
  time:
  zeit: 
  